var provinceDic = new Array();
provinceDic['全国'] = 0
provinceDic['北10'] = 1
provinceDic['南21'] = 2
provinceDic['北京'] = 3
provinceDic['天津'] = 4
provinceDic['河北'] = 5
provinceDic['山西'] = 6
provinceDic['内蒙古'] = 7
provinceDic['辽宁'] = 8
provinceDic['吉林'] = 9
provinceDic['黑龙江'] = 10
provinceDic['山东'] = 11
provinceDic['河南'] = 12
provinceDic['上海'] = 13
provinceDic['江苏'] = 14
provinceDic['浙江'] = 15
provinceDic['安徽'] = 16
provinceDic['福建'] = 17
provinceDic['江西'] = 18
provinceDic['湖北'] = 19
provinceDic['湖南'] = 20
provinceDic['广东'] = 21
provinceDic['广西'] = 22
provinceDic['海南'] = 23
provinceDic['重庆'] = 24
provinceDic['四川'] = 25
provinceDic['贵州'] = 26
provinceDic['云南'] = 27
provinceDic['西藏'] = 28
provinceDic['陕西'] = 29
provinceDic['甘肃'] = 30
provinceDic['青海'] = 31
provinceDic['宁夏'] = 32
provinceDic['新疆'] = 33
provinceDic['总部及子公司'] = 34

var provinceCodeDic = new Array();
provinceCodeDic[0] = '全国'
	provinceCodeDic[1] = '北10'
	provinceCodeDic[2] = '南21'
	provinceCodeDic[3] = '北京'
	provinceCodeDic[4] = '天津'
	provinceCodeDic[5] = '河北'
	provinceCodeDic[6] = '山西'
	provinceCodeDic[7] = '内蒙古'
	provinceCodeDic[8] = '辽宁'
	provinceCodeDic[9] = '吉林'
	provinceCodeDic[10] = '黑龙江'
	provinceCodeDic[11] = '山东'
	provinceCodeDic[12] = '河南'
	provinceCodeDic[13] = '上海'
	provinceCodeDic[14] = '江苏'
	provinceCodeDic[15] = '浙江'
	provinceCodeDic[16] = '安徽'
	provinceCodeDic[17] = '福建'
	provinceCodeDic[18] = '江西'
	provinceCodeDic[19] = '湖北'
	provinceCodeDic[20] = '湖南'
	provinceCodeDic[21] = '广东'
	provinceCodeDic[22] = '广西'
	provinceCodeDic[23] = '海南'
	provinceCodeDic[24] = '重庆'
	provinceCodeDic[25] = '四川'
	provinceCodeDic[26] = '贵州'
	provinceCodeDic[27] = '云南'
	provinceCodeDic[28] = '西藏'
	provinceCodeDic[29] = '陕西'
	provinceCodeDic[30] = '甘肃'
	provinceCodeDic[31] = '青海'
	provinceCodeDic[32] = '宁夏'
	provinceCodeDic[33] = '新疆'
	provinceCodeDic[34] = '总部及子公司'
		
var subjectDic = new Array();
subjectDic['全部业务'] = 0
subjectDic['新兴ICT'] = 1
subjectDic['物联网'] = 11
subjectDic['大数据'] = 12
subjectDic['IT服务'] = 13
subjectDic['IDC'] = 14
subjectDic['云计算（含CDN）'] = 15
subjectDic['移网基础业务'] = 2
subjectDic['固网基础业务'] = 3
subjectDic['互联网业务'] = 31
subjectDic['固话'] = 32
subjectDic['数据网元'] = 33
subjectDic['分摊固网其他收入'] = 34


var userSubjectDic = new Array();
userSubjectDic['当月主营收入'] = 1
userSubjectDic['出账用户'] = 2
userSubjectDic['当月净增用户'] = 3
userSubjectDic['累计净增用户'] = 4
userSubjectDic['当月新发展用户'] = 5
userSubjectDic['月流失用户'] = 6
userSubjectDic['基础ARPU'] = 7

var zhibiaoDic = new Array();
zhibiaoDic['当月收入'] = 1
zhibiaoDic['同比增幅'] = 2
zhibiaoDic['环比增幅'] = 3

var userZhibiaoDic = new Array();
userZhibiaoDic['指标值'] = 1
userZhibiaoDic['环比增幅'] = 2

var zhibiao2Dic = new Array();
zhibiao2Dic['主营收入占比(当月)'] = 'zysrzb'
zhibiao2Dic['主营收入ARPU'] = 'ARPU'
zhibiao2Dic['新兴ICT业务占大网比例（当月）'] = 'cxywzdw'
zhibiao2Dic['新兴ICT业务占集客整体收入比例'] = 'cxywzjk'
zhibiao2Dic['移动基础占集客整体收入比例'] = 'ydjczjk'
zhibiao2Dic['固网基础占集客整体收入比例'] = 'gwjczjk'
zhibiao2Dic['增量收入占公司大网增量收入的比值'] = 'zlsrzdw'